### ISSUE TITLE
Automatically set rows 

### ISSUE THREAD

**Issue by filburt** [ka215/jquery.timeline#10]
Hi,

Thanks for the great timeline! One Question: Is it possible that events which are generated from a database are automatically placed in separate rows if they have the same or overlapping dates?

Thanks a lot and regards,
Filburt

**Comment by ka215** [comment]
Hi there,

It is a wonderful idea to have duplicate events automatically placed on separate lines.

I think that I also want it, but thinking that it is difficult to implement at the moment because of the complexity of the algorithm when considering the case where it is arranged such that it exceeds the number of display lines set by the user beforehand.

Thanks,
