### ISSUE TITLE
Tooltips are not visible for the first row

### ISSUE THREAD

**Issue by rkorzeniewski** [ka215/jquery.timeline#46]
When playing with the demo of jQuery.Timeline at https://ka2.org/jqtl-v2/index.php when you toggle to display tooltips then tooltips for the first row are not displayed. Tooltips for any other rows are.

**Comment by ka215** [comment]
Hi there,

I saw that as per your instructions. However, I could not reproduce the trouble you said as follows the image.

![screenshot](https://ka2.org/assets/uploads/files/jqtl-v2_demo1.jpg)

On that demo, any events only that does not have thumbnail image are available to the tooltips.

Perhaps maybe there has been occurred degradation by other bugs of the previous version, too.

Please try to check once more.
Thank you,

**Comment by rkorzeniewski** [comment]
@ka215 Please switch to "BAR" then toggle "Tooltips" and not "Popovers" (which are working as expected). I'm using the following Demo url: https://ka2.org/jqtl-v2/index.php which is not titled "Marver ..." but a "Demo of jQuery.Timeline" using version 2.0.0b2. Thanks.

**Comment by ka215** [comment]
I'm sorry to mistake the demo page. I saw correctly specified demo page. Yet, I did not find the trouble as like follows images.

![v2.0.0b2 with bar](https://ka2.org/assets/uploads/files/jqtl-v2_tooltip_bar.png)

![v2.0.0b2 with point](https://ka2.org/assets/uploads/files/jqtl-v2_tooltip_point.png)

Also, we should set on the bootstrap when checking to available the modal, popover, and tooltip on that demo.

Thank you,

**Comment by rkorzeniewski** [comment]
@ka215 I'm using: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Please select bootstrap version 3, bars and any jQuery version then check again. Yes, tooltips with bootstrap version 4 are working as expected.

**Comment by ka215** [comment]
Hi, I saw the trouble, as you said. Thank you for getting the clues.

That cause was due to the position of the tooltip element added by the bootstrap 3. At the bootstrap of the less than version 4, there is added a tooltip element just after trigger fired element. Therefore some tooltip element is overflowed in container element then hidden. But since version 4, the tooltip element is appended to the last of a body element then there is not affected by the events container element as a parent.

If we use the tooltip of bootstrap3 with this timeline, we should set the "placement" option that excepts "top" to any events on the first row. I recommended using bootstrap 4 because of outdated ver.3. 

Thank you,
